micronaut:
  application:
    name: desafioPix
datasources:
  default:
    url: jdbc:postgresql://localhost:5433/desafio_pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
externo:
  erp: ${ItauErp_url:`http://localhost:9091`}